version: "3"
services:
  python:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: python main.py
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.0.15
